name: Manual workflow

on:
  workflow_dispatch:
    inputs: { }
jobs:
  prepare_content:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: |
          pwd
          ls -la
      - name: Execute script
        run: ./my-script.sh