name: Manual workflow

on:
  workflow_dispatch:
    inputs: {}
jobs:
  prepare_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GH_TOKEN_MULTI }}
      - name: Print env
        run: |
          pwd
          ls -la
      - name: Execute script
        run: ./my-script.sh