name: "2-Update-roles-and-permissions-docs"

on:
  workflow_dispatch:
    inputs: { }
env:
  CONFLUENCE_PAGE_ID: "116069632"
  CASBINCSV_CONFIG_FILE: "./commons/rbac/src/main/resources/rbac.casbincsv"
  API_PATH: "https://vanft.daimler.com/confluence"
jobs:
  update-roles-and-permissions-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare content
        run: |
          DATA_ROWS=""
          INDEX="1"
          
          # Parse each not empty and non-comment line from casbincsv config file and build HTML table row markup
          while read -r line; do
            if [[ ${#line} -gt 0 ]] && ! [[ "$line" =~ ^# ]]; then
              IFS=', ' read -r -a permit_line <<<"$line"
              DATA_ROWS+="<tr><td>$INDEX</td><td>${permit_line[1]}</td><td>${permit_line[3]}</td><td>${permit_line[4]}</td></tr>"
              INDEX=$((INDEX+1))
            fi
          done <"$CASBINCSV_CONFIG_FILE"
          
          # Build HTML table markup
          HEADER_ROW="<tr><th>#<b></b></th><th><b>Role</b></th><th><b>Scope</b></th><th><b>Permit</b></th></tr>"
          TABLE_CONTENT="<table><thead>$HEADER_ROW</thead><tbody>$DATA_ROWS</tbody></table>"
          
          # Pass to the next steps
          echo "TABLE_CONTENT=$TABLE_CONTENT" >> $GITHUB_ENV
      - name: Get current page info
        env:
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
        run: |
          # Get current page info. Space and title are required for update request. New page version also must be incremented manually 
          RESPONSE=$(curl -s -X GET \
            -H "Authorization: Bearer $CONFLUENCE_TOKEN" \
            "$API_PATH/rest/api/content/$CONFLUENCE_PAGE_ID?expand=version,space")
          
          PAGE_VERSION=$(jq -r '.version.number' <<<"$RESPONSE")
          SPACE=$(jq -r '.space.key' <<<"$RESPONSE")
          PAGE_TITLE=$(jq -r '.title' <<<"$RESPONSE")
          NEW_PAGE_VERSION=$((PAGE_VERSION + 1))
          
          # Pass to the next steps
          echo "NEW_PAGE_VERSION=$NEW_PAGE_VERSION" >> $GITHUB_ENV
          echo "SPACE=$SPACE" >> $GITHUB_ENV
          echo "PAGE_TITLE=$PAGE_TITLE" >> $GITHUB_ENV
      - name: Update page
        env:
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
        run: |
          curl -X PUT \
            -H "Authorization: Bearer $CONFLUENCE_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
                      \"id\":\"$CONFLUENCE_PAGE_ID\",
                      \"type\":\"page\",
                      \"title\":\"$PAGE_TITLE\",
                      \"version\":{\"number\":\"$NEW_PAGE_VERSION\"},
                      \"space\":{\"key\":\"$SPACE\"},
                      \"body\":{
                          \"storage\":{
                              \"value\":\"$TABLE_CONTENT\",
                              \"representation\":\"storage\"
                          }
                      }
                   }" \
            "$API_PATH/rest/api/content/$CONFLUENCE_PAGE_ID"
